### ISSUE TITLE
August 25th Meetup at Red Collar

### ISSUE THREAD

**Issue by chrisfosterelli** [kamloopsjs/general#10]
Running suggestions:
* Nodeschool event
* Pub meetup
* RethinkDB
* Coffeescript
* ES6
* Webpack/browserify/etc.

**Comment by jonotron** [comment]
Thurs Aug 25th 5-6pm, meetup at Red Collar! Yay/nay?

August will be hard to plan a talk and attendance will be iffy with so many people on vacation. This is easy to plan.

**Comment by chrisfosterelli** [comment]
@jonotron Works for me!

**Comment by jonotron** [comment]
I've confirmed with Red Collar. So good to go there.

**Comment by chadfawcett** [comment]
I think an event page would be nice since not everyone is following this repo.

**Comment by jonotron** [comment]
Ya, I think an event page would be handy. Plus, it reminds folks day of: https://www.picatic.com/kamloopsjsmeetupSept2016
