### ISSUE TITLE
Oct Talk

### ISSUE THREAD

**Issue by jonotron** [kamloopsjs/general#12]
@chadfawcett said he'd like to do a talk on physical js on rasp pi. Sounds great to me!

**Comment by chadfawcett** [comment]
I was thinking something along the lines of interfacing physical things (buttons, sensors, etc) with the web using Javascript.

**Comment by jonotron** [comment]
Thoughts on Oct 27th?

**Comment by chadfawcett** [comment]
That'll work.

**Comment by chadfawcett** [comment]
So I don't have the hardware that I would have liked for the idea I had in mind. How about an intro to continuous integration/deployment using Semaphore? Automated testing, building, and deployment of a node app.

**Comment by jonotron** [comment]
Sounds great! Let's do it. Make a short writeup and I'll schedule the events and emails.

**Comment by jonotron** [comment]
Ticket page: https://www.picatic.com/kamloopsjs-ci-semaphore

**Comment by jonotron** [comment]
Email scheduled for Monday morning.
