### ISSUE TITLE
January 2015 Meetup

### ISSUE THREAD

**Issue by arasbm** [kamloopsjs/general#7]
I cant believe 2014 is almost over already! Lets see if we can squeeze another JavaScript meetup in. I recommend sometime in the second week of December. 
I am already planning a maker workshop on Wednesday Dec 10th. But any other day around that time would work for me.

It would be awesome if we could convince @davidpp to give a talk :)

Let me know what day you think would be good and if you know anyone else that would be interested in speakiong. Two speakers per event seems to work really well so far.

**Comment by chrisfosterelli** [comment]
Any updates on this?

**Comment by jonotron** [comment]
@davidpp Any idea on a topic? We'd like to start getting the word out.

**Comment by davidpp** [comment]
Hi Guys!




I’m sorry if I didn’t answer before.  I have to postpone my talk, I’m in a unexpected big rush for work until the end of the month and don’t think I’ll have enough free time to put together something to talk about.


David Paquet Pitts. Associé. Partner.

T.  514-400-3750 #177




∆




okam.ca  instinct numérique.  digital instinct.




QC.  408 Saint Sulpice, Suite 1, Montréal  H2Y 2V5

BC.  348 Tranquille Road, Kamloops  V2B 3G8

**Comment by jonotron** [comment]
Fair enough. Shall we aim to do a nodeschool instead? Maybe on Jan 20?

**Comment by chrisfosterelli** [comment]
I'm down for that!

**Comment by arasbm** [comment]
That is a good idea. I don’t think I can be much help though since all my
free time is going into Kamloops Makerspace. Just so you know, we are
having a workshop on Wednesday January 21st for makerspace.

**Comment by jonotron** [comment]
Closing
