### ISSUE TITLE
Jan 27th, 2016 - Intro to Docker

### ISSUE THREAD

**Issue by jonotron** [kamloopsjs/general#8]
So I still want to see Kamloops.js as a group that does actual things :) People are busy, organizing is hard.

I'm proposing a meetup in the new year where @syncopated comes up from Salmon Arm and drops vim and tmux knowledge on us. I think the @trucsclub would be interested in the topic as @chrisfosterelli once wanted to run a vim workshop.

If that's not desired, @syncopated also has some background with socket.io.

Any thoughts?

**Comment by jonotron** [comment]
@syncopated, I just picked that date out of a hat... feel free to suggest something else or decline entirely :) no pressure.

**Comment by chrisfosterelli** [comment]
I thought you had some good criticism with the Vim idea, because it's a hard thing to "teach" in a workshop and is moreso something you have a play with and get experience with over time. However, I think students would greatly benefit from seeing how extensible vim can actually be (rather than the locked down version they have access to on the school servers) and I've had students ask about it before.

Whatever the event is, the club would definitely be interested in advertising it!

**Comment by jonotron** [comment]
Optionally, I could do a Docker + DO session (intro to docker, plus running it on digital ocean... we have a bunch of DO t-shirts still to give away)

**Comment by chrisfosterelli** [comment]
That sounds cool!

**Comment by syncopated** [comment]
That date sounds fine to me. I'm flexible on the topic and would love to learn more about Docker.
I could talk about remote work maybe -- tmux and vim could make a cameo there :)

**Comment by jonotron** [comment]
I've just started working with a new client right now and Docker is likely going to play into that a bit, so unless anyone objects, I think I would like to do the Jan session on Docker. @syncopated how does March sound for you to talk about remote + tmux + vim?

**Comment by syncopated** [comment]
Sounds good. I'm going to be away for Spring Break so it would have to be in the first couple weeks of March (before the 11th).

**Comment by jonotron** [comment]
Does Jan 27th work for TRUCS club? Topic: intro to docker

**Comment by chrisfosterelli** [comment]
@jonotron This doesn't conflict with any of our events, and I'd be happy to advertise this for you.

**Comment by chrisfosterelli** [comment]
Is there an event page for this yet?

**Comment by jonotron** [comment]
https://www.picatic.com/kamloopsjs-docker

**Comment by chrisfosterelli** [comment]
Thanks!
