### ISSUE TITLE
July event

### ISSUE THREAD

**Issue by jonotron** [kamloopsjs/general#9]
We are hoping to plan a nodeschool event in June (https://github.com/nodeschool/kamloops/issues/5). What are thoughts on doing a kamloopsjs talk in July? Perhaps we can finally get @syncopated to come and do a show :) Thoughts on Thursday July 21st 5-6pm?

**Comment by chrisfosterelli** [comment]
That date sounds solid to me :+1:

**Comment by syncopated** [comment]
That date sounds good to me too. I'd plan to come either way.

**Comment by chrisfosterelli** [comment]
Great, let's plan for that then!

**Comment by jonotron** [comment]
@syncopated How does July 21st work for you? Still want to do a fun JS talk? Any topics come to mind?

**Comment by syncopated** [comment]
Yes, the 21st works. Could talk about ES6 & webpack, node/angular/socket.io (go over the tech behind stance.com) or ?
I'm open to suggestions and would be up for having a discussion about JS stuff in general too.

**Comment by jonotron** [comment]
@syncopated Awesome. Let's do stance.com tech stack. I'll check on venue, but lets plan for Kamloops Innovation Centre in the co-working space 5-6pm

**Comment by syncopated** [comment]
Sweet sounds good!

**Comment by jonotron** [comment]
Ticket site up:

https://www.picatic.com/event14678266277095

@syncopated if you want to give me a little teaser I will update the event details.

**Comment by chrisfosterelli** [comment]
@jonotron Just so you know, registration says 'Closed'

**Comment by jonotron** [comment]
Woops… fixed

**Comment by chrisfosterelli** [comment]
Thanks again @syncopated!
